package nl.xx1.whatsapp4j.model;

import com.google.gson.annotations.SerializedName;

public enum MessageType {
    @SerializedName("chat")
    TEXT,
    @SerializedName("audio")
    AUDIO,
    @SerializedName("voice")
    VOICE,
    @SerializedName("image")
    IMAGE,
    @SerializedName("video")
    VIDEO,
    @SerializedName("document")
    DOCUMENT,
    @SerializedName("sticker")
    STICKER,
    @SerializedName("location")
    LOCATION,
    @SerializedName("contact_card")
    CONTACT_CARD,
    @SerializedName("contact_card_multi")
    CONTACT_CARD_MULTI,
    @SerializedName("order")
    ORDER,
    @SerializedName("revoked")
    REVOKED,
    @SerializedName("product")
    PRODUCT,
    @SerializedName("unknown")
    UNKNOWN,
    @SerializedName("group_invite")
    GROUP_INVITE,
    @SerializedName("list")
    LIST,
    @SerializedName("list_response")
    LIST_RESPONSE,
    @SerializedName("buttons_response")
    BUTTONS_RESPONSE,
    @SerializedName("payment")
    PAYMENT,
    @SerializedName("broadcast_notification")
    BROADCAST_NOTIFICATION,
    @SerializedName("call_log")
    CALL_LOG,
    @SerializedName("ciphertext")
    CIPHERTEXT,
    @SerializedName("debug")
    DEBUG,
    @SerializedName("e2e_notification")
    E2E_NOTIFICATION,
    @SerializedName("gp2")
    GP2,
    @SerializedName("group_notification")
    GROUP_NOTIFICATION,
    @SerializedName("hsm")
    HSM,
    @SerializedName("interactive")
    INTERACTIVE,
    @SerializedName("native_flow")
    NATIVE_FLOW,
    @SerializedName("notification")
    NOTIFICATION,
    @SerializedName("notification_template")
    NOTIFICATION_TEMPLATE,
    @SerializedName("oversized")
    OVERSIZED,
    @SerializedName("protocol")
    PROTOCOL,
    @SerializedName("reaction")
    REACTION,
    @SerializedName("template_button_reply")
    TEMPLATE_BUTTON_REPLY,
    @SerializedName("poll_creation")
    POLL_CREATION
}
